openapi: 3.0.0
info:
  title: Quest API
  description: API for Quest task management system
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Development server
  - url: https://api.quest.app/v1
    description: Production server

components:
  schemas:
    User:
      type: object
      required:
        - email
        - name
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 255
        name:
          type: string
          maxLength: 100
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true

    List:
      type: object
      required:
        - name
        - user_id
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 50
        is_system:
          type: boolean
          description: "True for system lists (daily, weekly, backlog, history)"
        system_type:
          type: string
          enum: [daily, weekly, backlog, history, custom]
          description: "Type of system list, or 'custom' for user-created lists"
          readOnly: true
        position:
          type: integer
        user_id:
          type: string
          format: uuid
          description: "ID of the user who owns this list"
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true

    Task:
      type: object
      required:
        - title
        - list_id
        - user_id
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        title:
          type: string
          maxLength: 100
        description:
          type: string
          description: Markdown formatted description
        list_id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
          description: "ID of the user who owns this task"
        status:
          type: string
          enum: [todo, done, archived]
          default: todo
          description: "Task status: todo (active), done (completed but visible), archived (completed and moved to history)"
        due_date:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
          readOnly: true
        completed_at:
          type: string
          format: date-time
          readOnly: true
          description: "When the task was marked as done"
        archived_at:
          type: string
          format: date-time
          readOnly: true
          description: "When the task was moved to history (automatic for daily/weekly tasks)"
        original_list_id:
          type: string
          format: uuid
          description: "Reference to the original list where the task was created, preserved for history"
        repeat_type:
          type: string
          enum: [none, after_completion, fixed_schedule]
          description: "none: one-time task, after_completion: repeats after being done, fixed_schedule: repeats on schedule"
          default: none
        repeat_value:
          type: integer
          minimum: 1
          description: The number of time units to repeat after
        repeat_frequency:
          type: string
          enum: [hours, days, weeks, months, years]
        position:
          type: integer
          description: Position in the list
        labels:
          type: array
          items:
            $ref: '#/components/schemas/Label'

    Label:
      type: object
      required:
        - name
        - color
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 20
        color:
          type: string
          pattern: '^#[0-9a-fA-F]{6}$'
          description: Hexadecimal color code
        created_at:
          type: string
          format: date-time
          readOnly: true

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    ListId:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
    TaskId:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
    LabelId:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid

security:
  - BearerAuth: []

paths:
  /auth/login:
    post:
      summary: User login
      security: []  # No authentication required for login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  expires_in:
                    type: integer
                    description: "Token expiry in seconds (72h = 259200)"
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Invalid credentials

  /auth/register:
    post:
      summary: User registration
      security: []  # No authentication required for registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - name
                - password
              properties:
                email:
                  type: string
                  format: email
                name:
                  type: string
                  maxLength: 100
                password:
                  type: string
                  minLength: 8
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  expires_in:
                    type: integer
                  user:
                    $ref: '#/components/schemas/User'

  /auth/refresh:
    post:
      summary: Refresh access token
      security: []  # Uses refresh token instead
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refresh_token
              properties:
                refresh_token:
                  type: string
      responses:
        '200':
          description: Token refreshed
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  expires_in:
                    type: integer

  /lists:
    get:
      summary: List all lists for current user
      responses:
        '200':
          description: List of lists
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/List'
    post:
      summary: Create a new list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  maxLength: 50
                position:
                  type: integer
      responses:
        '201':
          description: List created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/List'

  /lists/{id}:
    parameters:
      - $ref: '#/components/parameters/ListId'
    get:
      summary: Get list details with tasks
      responses:
        '200':
          description: List details
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/List'
                  - type: object
                    properties:
                      tasks:
                        type: array
                        items:
                          $ref: '#/components/schemas/Task'
    put:
      summary: Update list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 50
                position:
                  type: integer
      responses:
        '200':
          description: List updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/List'
    delete:
      summary: Delete list
      description: "Cannot delete system lists (daily, weekly, backlog, history)"
      responses:
        '204':
          description: List deleted
        '400':
          description: Cannot delete system list

  /tasks:
    get:
      summary: List all tasks
      parameters:
        - name: list_id
          in: query
          schema:
            type: string
            format: uuid
          description: "Filter tasks by list ID"
        - name: list_type
          in: query
          schema:
            type: string
            enum: [daily, weekly, backlog, history]
          description: "Filter tasks by list type"
        - name: completed_before
          in: query
          schema:
            type: string
            format: date-time
          description: "Filter tasks completed before this date"
        - name: completed_after
          in: query
          schema:
            type: string
            format: date-time
          description: "Filter tasks completed after this date"
        - name: original_list_id
          in: query
          schema:
            type: string
            format: uuid
          description: "Filter archived tasks by their original list"
        - name: status
          in: query
          schema:
            type: string
            enum: [todo, done, archived]
        - name: due_before
          in: query
          schema:
            type: string
            format: date-time
        - name: due_after
          in: query
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - list_id
              properties:
                title:
                  type: string
                  maxLength: 100
                description:
                  type: string
                list_id:
                  type: string
                  format: uuid
                due_date:
                  type: string
                  format: date-time
                repeat_type:
                  type: string
                  enum: [none, after_completion, fixed_schedule]
                  default: none
                repeat_value:
                  type: integer
                  minimum: 1
                repeat_frequency:
                  type: string
                  enum: [hours, days, weeks, months, years]
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /tasks/{id}:
    parameters:
      - $ref: '#/components/parameters/TaskId'
    get:
      summary: Get task details
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    put:
      summary: Update task details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    delete:
      summary: Delete task
      responses:
        '204':
          description: Task deleted

  /tasks/{id}/status:
    parameters:
      - $ref: '#/components/parameters/TaskId'
    patch:
      summary: Update task status
      description: "Mark task as done. Tasks in daily/weekly lists will be automatically archived at their respective cutoff times"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum: [todo, done]
                  description: "Cannot manually set status to 'archived'. Non-recurring tasks are automatically archived. Recurring tasks are never archived and show progress until next occurrence."
      responses:
        '200':
          description: Status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /tasks/{id}/position:
    parameters:
      - $ref: '#/components/parameters/TaskId'
    patch:
      summary: Update task position
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - position
                - list_id
              properties:
                position:
                  type: integer
                list_id:
                  type: string
                  format: uuid
                  description: "Target list ID to move the task to"
      responses:
        '200':
          description: Position updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /labels:
    get:
      summary: List all labels
      responses:
        '200':
          description: List of labels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Label'
    post:
      summary: Create a new label
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Label'
      responses:
        '201':
          description: Label created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Label'

  /labels/{id}:
    parameters:
      - $ref: '#/components/parameters/LabelId'
    put:
      summary: Update label
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Label'
      responses:
        '200':
          description: Label updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Label'
    delete:
      summary: Delete label
      responses:
        '204':
          description: Label deleted

  /tasks/{id}/labels:
    parameters:
      - $ref: '#/components/parameters/TaskId'
    post:
      summary: Add label to task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - label_id
              properties:
                label_id:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Label added to task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /tasks/{taskId}/labels/{labelId}:
    parameters:
      - name: taskId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: labelId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    delete:
      summary: Remove label from task
      responses:
        '204':
          description: Label removed from task
